window.HF_DATA = {
  /** 14 角色：13 位 Google Drive Sora 英雄 + 全新龍騎士 */
  heroes: [
    {
      id: "knight",
      name: "騎士",
      color: "#90caf9",
      weapon: "長劍與盾",
      flavor: "命運由劍開路。",
      victory: ["衝刺前進！", "聖劍高舉！", "一刀兩斷！", "魔王倒地！", "VICTORY"],
    },
    {
      id: "paladin",
      name: "聖騎士",
      color: "#ffd54f",
      weapon: "聖錘與盾",
      flavor: "光與你同在。",
      victory: ["祈禱……", "聖光灌注！", "審判一擊！", "邪暗消散！", "VICTORY"],
    },
    {
      id: "ranger",
      name: "遊俠",
      color: "#81c784",
      weapon: "長弓",
      flavor: "第三箭，已經在路上。",
      victory: ["拉滿弓弦！", "三連貫穿！", "要害命中！", "收弓定格！", "VICTORY"],
    },
    {
      id: "orc_archer",
      name: "半獸人射手",
      color: "#9ccc65",
      weapon: "戰弓",
      flavor: "哈！這一箭，砸穿命運！",
      victory: ["戰吼！！", "連射重矢！", "貫穿敵陣！", "勝利大笑！", "VICTORY"],
    },
    {
      id: "axeman",
      name: "斧戰士",
      color: "#43a047",
      weapon: "巨斧",
      flavor: "一斧，定勝負。",
      victory: ["蓄力！", "迴旋斬！", "大地震裂！", "勝利咆哮！", "VICTORY"],
    },
    {
      id: "amazon",
      name: "女戰士",
      color: "#ff8a65",
      weapon: "鏈錘",
      flavor: "戰場，由我踩碎。",
      victory: ["旋風起！", "鏈錘轟擊！", "地面碎裂！", "勝者宣言！", "VICTORY"],
    },
    {
      id: "dark_fighter",
      name: "暗黑武鬥家",
      color: "#ef5350",
      weapon: "雙拳",
      flavor: "熱血——超載！",
      victory: ["戰意爆發！", "連擊轟碎！", "火焰氣功！", "一擊粉碎！", "VICTORY"],
    },
    {
      id: "assassin",
      name: "黑袍刺客",
      color: "#ab47bc",
      weapon: "紫影短刃",
      flavor: "……結束了。",
      victory: ["影遁……", "背後現身！", "致命背刺！", "收刀離去。", "VICTORY"],
    },
    {
      id: "archmage",
      name: "大魔導師",
      color: "#b39ddb",
      weapon: "紫晶法杖",
      flavor: "計算完畢，你輸了。",
      victory: ["詠唱開始……", "奧術洪流！", "爆裂閃光！", "化為灰燼！", "VICTORY"],
    },
    {
      id: "dark_mage",
      name: "黑暗法師",
      color: "#7e57c2",
      weapon: "闇晶法杖",
      flavor: "黑暗，才是答案。",
      victory: ["闇咒啟動……", "魔王降臨！", "虛空撕裂！", "一切歸零。", "VICTORY"],
    },
    {
      id: "dark_elf",
      name: "黑暗精靈",
      color: "#66bb6a",
      weapon: "毒綠法杖",
      flavor: "暗影之森，早已選定獵物。",
      victory: ["暗影綻放……", "毒藤纏繞！", "咒印炸裂！", "沉入永夜。", "VICTORY"],
    },
    {
      id: "monk",
      name: "僧侶",
      color: "#fff59d",
      weapon: "聖鈴錫杖",
      flavor: "願光指引迷途者。",
      victory: ["誦經……", "聖鈴一響！", "淨化之光！", "安魂安息。", "VICTORY"],
    },
    {
      id: "princess",
      name: "公主",
      color: "#f48fb1",
      weapon: "星光權杖",
      flavor: "皇家榮耀，不允許失敗。",
      victory: ["禮服一揚！", "星光飛舞！", "皇家裁決！", "優雅致意。", "VICTORY"],
    },
    {
      id: "dragon_knight",
      name: "龍騎士",
      color: "#4dd0e1",
      weapon: "龍焰長槍",
      flavor: "龍焰所指，命運俯首。",
      victory: ["龍魂覺醒！", "焰槍破陣！", "蒼龍貫天！", "王座俯首！", "VICTORY"],
    },
  ],
};
